### ISSUE TITLE
Examples `piano` and `input` panic at runtime

### ISSUE THREAD

**Issue by dsgallups** [BlackPhlox/bevy_midi#42]
Running `examples/piano`:
```console
     Running `target/debug/examples/piano`
2024-12-05 21:40:37.755 piano[73303:2168281] +[IMKClient subclass]: chose IMKClient_Modern
2024-12-05 21:40:37.755 piano[73303:2168281] +[IMKInputSession subclass]: chose IMKInputSession_Modern
thread '<unnamed>' panicked at src/input.rs:246:55:
index out of bounds: the len is 1 but the index is 1
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
zsh: abort      cargo run --example piano
```
-----
## Connecting to digital keyboard (port 0) running `examples/input`:
```console
     Running `target/debug/examples/input`
2024-12-05 21:38:42.904 input[72286:2158221] +[IMKClient subclass]: chose IMKClient_Modern
2024-12-05 21:38:42.904 input[72286:2158221] +[IMKInputSession subclass]: chose IMKInputSession_Modern
thread '<unnamed>' panicked at src/input.rs:246:55:
index out of bounds: the len is 1 but the index is 1
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
zsh: abort      cargo run --example input
 ```
 
 ## System Info
 `Darwin Mac 24.1.0 Darwin Kernel Version 24.1.0: Thu Oct 10 21:05:23 PDT 2024; root:xnu-11215.41.3~2/RELEASE_ARM64_T6031 arm64`
 ```console
 Default host: aarch64-apple-darwin
rustup home:  /Users/danielgallups/.rustup

installed toolchains
--------------------

stable-aarch64-apple-darwin (default)
nightly-aarch64-apple-darwin
1.79-aarch64-apple-darwin

installed targets for active toolchain
--------------------------------------

aarch64-apple-darwin
wasm32-unknown-unknown

active toolchain
----------------

stable-aarch64-apple-darwin (default)
rustc 1.83.0 (90b35a623 2024-11-26)
```

**Comment by dsgallups** [comment]
Inspecting the stream of messages, I went to see what was going on. Definitely a continuous stream, and I played a few keys quickly in succession in between:

```console
2024-12-06T04:07:37.668319Z  INFO bevy_midi::input: Stamp: 46801051015; Message: 11111000 ([248])
2024-12-06T04:07:37.689314Z  INFO bevy_midi::input: Stamp: 46801072011; Message: 11111000 ([248])
2024-12-06T04:07:37.711335Z  INFO bevy_midi::input: Stamp: 46801094032; Message: 11111000 ([248])
2024-12-06T04:07:37.715290Z  INFO bevy_midi::input: Stamp: 46801098000; Message: 11111110 ([254])
2024-12-06T04:07:37.732307Z  INFO bevy_midi::input: Stamp: 46801115005; Message: 11111000 ([248])
2024-12-06T04:07:37.744361Z  INFO bevy_midi::input: Stamp: 46801127059; Message: 10010000 00111100 00111101 ([144, 60, 61])
2024-12-06T04:07:37.753424Z  INFO bevy_midi::input: Stamp: 46801136069; Message: 11111000 ([248])
2024-12-06T04:07:37.755313Z  INFO bevy_midi::input: Stamp: 46801138012; Message: 10010000 01000000 00000000 ([144, 64, 0])
2024-12-06T04:07:37.774348Z  INFO bevy_midi::input: Stamp: 46801157041; Message: 11111000 ([248])
2024-12-06T04:07:37.795468Z  INFO bevy_midi::input: Stamp: 46801178113; Message: 11111000 ([248])
2024-12-06T04:07:37.817301Z  INFO bevy_midi::input: Stamp: 46801200006; Message: 11111000 ([248])
2024-12-06T04:07:37.827395Z  INFO bevy_midi::input: Stamp: 46801210062; Message: 10010000 00111100 00000000 ([144, 60, 0])
2024-12-06T04:07:37.835336Z  INFO bevy_midi::input: Stamp: 46801218038; Message: 10010000 01000000 01011001 ([144, 64, 89])
2024-12-06T04:07:37.838288Z  INFO bevy_midi::input: Stamp: 46801220999; Message: 11111000 ([248])
2024-12-06T04:07:37.859329Z  INFO bevy_midi::input: Stamp: 46801242001; Message: 11111000 ([248])
2024-12-06T04:07:37.880345Z  INFO bevy_midi::input: Stamp: 46801263023; Message: 11111000 ([248])
2024-12-06T04:07:37.901382Z  INFO bevy_midi::input: Stamp: 46801284068; Message: 11111000 ([248])
2024-12-06T04:07:37.915375Z  INFO bevy_midi::input: Stamp: 46801298036; Message: 11111110 ([254])
2024-12-06T04:07:37.922303Z  INFO bevy_midi::input: Stamp: 46801305009; Message: 10010000 00111100 01000101 ([144, 60, 69])
2024-12-06T04:07:37.923282Z  INFO bevy_midi::input: Stamp: 46801305996; Message: 11111000 ([248])
2024-12-06T04:07:37.939317Z  INFO bevy_midi::input: Stamp: 46801322023; Message: 10010000 01000000 00000000 ([144, 64, 0])
2024-12-06T04:07:37.944279Z  INFO bevy_midi::input: Stamp: 46801326989; Message: 11111000 ([248])
2024-12-06T04:07:37.965438Z  INFO bevy_midi::input: Stamp: 46801348096; Message: 11111000 ([248])
2024-12-06T04:07:37.986328Z  INFO bevy_midi::input: Stamp: 46801369025; Message: 11111000 ([248])
2024-12-06T04:07:38.005479Z  INFO bevy_midi::input: Stamp: 46801388123; Message: 10010000 00111100 00000000 ([144, 60, 0])
2024-12-06T04:07:38.006291Z  INFO bevy_midi::input: Stamp: 46801389003; Message: 10010000 01000000 01001101 ([144, 64, 77])
2024-12-06T04:07:38.007285Z  INFO bevy_midi::input: Stamp: 46801389999; Message: 11111000 ([248])
2024-12-06T04:07:38.029301Z  INFO bevy_midi::input: Stamp: 46801412001; Message: 11111000 ([248])
2024-12-06T04:07:38.050352Z  INFO bevy_midi::input: Stamp: 46801433020; Message: 11111000 ([248])
2024-12-06T04:07:38.071335Z  INFO bevy_midi::input: Stamp: 46801454030; Message: 11111000 ([248])
2024-12-06T04:07:38.085352Z  INFO bevy_midi::input: Stamp: 46801468042; Message: 10010000 00111100 00111100 ([144, 60, 60])
2024-12-06T04:07:38.092328Z  INFO bevy_midi::input: Stamp: 46801475029; Message: 11111000 ([248])
2024-12-06T04:07:38.104330Z  INFO bevy_midi::input: Stamp: 46801487031; Message: 10010000 01000000 00000000 ([144, 64, 0])
2024-12-06T04:07:38.113288Z  INFO bevy_midi::input: Stamp: 46801496000; Message: 11111000 ([248])
2024-12-06T04:07:38.115271Z  INFO bevy_midi::input: Stamp: 46801497986; Message: 11111110 ([254])
2024-12-06T04:07:38.135477Z  INFO bevy_midi::input: Stamp: 46801518154; Message: 11111000 ([248])
2024-12-06T04:07:38.156438Z  INFO bevy_midi::input: Stamp: 46801539086; Message: 11111000 ([248])
2024-12-06T04:07:38.163296Z  INFO bevy_midi::input: Stamp: 46801546003; Message: 10010000 01000000 00111100 ([144, 64, 60])
2024-12-06T04:07:38.166323Z  INFO bevy_midi::input: Stamp: 46801549029; Message: 10010000 00111100 00000000 ([144, 60, 0])
2024-12-06T04:07:38.177325Z  INFO bevy_midi::input: Stamp: 46801560017; Message: 11111000 ([248])
2024-12-06T04:07:38.198380Z  INFO bevy_midi::input: Stamp: 46801581063; Message: 11111000 ([248])
2024-12-06T04:07:38.219328Z  INFO bevy_midi::input: Stamp: 46801602027; Message: 11111000 ([248])
2024-12-06T04:07:38.232329Z  INFO bevy_midi::input: Stamp: 46801615025; Message: 10010000 00111100 01000011 ([144, 60, 67])
2024-12-06T04:07:38.241314Z  INFO bevy_midi::input: Stamp: 46801624011; Message: 11111000 ([248])
2024-12-06T04:07:38.254347Z  INFO bevy_midi::input: Stamp: 46801637048; Message: 10010000 01000000 00000000 ([144, 64, 0])
2024-12-06T04:07:38.262341Z  INFO bevy_midi::input: Stamp: 46801645018; Message: 11111000 ([248])
2024-12-06T04:07:38.283430Z  INFO bevy_midi::input: Stamp: 46801666101; Message: 11111000 ([248])
2024-12-06T04:07:38.304398Z  INFO bevy_midi::input: Stamp: 46801687074; Message: 11111000 ([248])
2024-12-06T04:07:38.309306Z  INFO bevy_midi::input: Stamp: 46801692017; Message: 10010000 00111100 00000000 ([144, 60, 0])
2024-12-06T04:07:38.315290Z  INFO bevy_midi::input: Stamp: 46801697994; Message: 11111110 ([254])
2024-12-06T04:07:38.320308Z  INFO bevy_midi::input: Stamp: 46801703010; Message: 10010000 01000000 01001001 ([144, 64, 73])
2024-12-06T04:07:38.326284Z  INFO bevy_midi::input: Stamp: 46801708994; Message: 11111000 ([248])
2024-12-06T04:07:38.347377Z  INFO bevy_midi::input: Stamp: 46801730048; Message: 11111000 ([248])
```
